'use client'
import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react'
import { Search } from 'lucide-react'
import Image from 'next/legacy/image'
import Weather from './weather'

export default function Home() {

  const [city , setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loading , setLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
  
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name='desciption' content='Generated by Omm Shah' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />

        <Image 
        src={"https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1975&q=80"}
        alt="clear sky"
        layout='fill'
        className='object-cover'
        />

        <div className='space-y-5'>

      {/* Search */}
      <div className='relative flex justify-center items-center w-full margin-auto pt-4 text-white z-10'>


        <form 
        onSubmit={fetchWeather}
        className='flex border-2 border-gray-300 bg-gray-300/50 p-2 rounded-2xl'
        >
          <div>
            <input 
            type="text" 
            placeholder='Search City' 
            className='bg-transparent text-black focus:outline-none placeholder:text-black w-96 overflow-clip'
            onChange={(e) => {setCity(e.target.value)}}
            />
          </div>
          <button onClick={fetchWeather}><Search className='text-black' /></button>
        </form>
      </div>

      {/* Weather */}

      {weather.main && <Weather data={weather} />}

      </div>

    </div>
  )
}
